services:
  postgresql-master:
    image: docker.io/bitnami/postgresql:13
    ports:
      - 5432:5432/tcp
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql/13'
      - './setup.sql:/docker-entrypoint-initdb.d/setup.sql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=sample
      - ALLOW_EMPTY_PASSWORD=yes
  postgresql-slave:
    image: docker.io/bitnami/postgresql:13
    ports:
      - 5433:5432/tcp
    volumes:
      - ./pg_hba.conf:/bitnami/postgresql/conf/pg_hba.conf
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_USERNAME=slave
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_PGHBA_REMOVE_FILTERS=local
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  postgresql_master_data:
    driver: local

